[build]
  command = "npm run build"
  publish = "dist"

[context.production.environment]
  VITE_GOOGLE_SCRIPT_URL = "${VITE_GOOGLE_SCRIPT_URL}"
  VITE_GOOGLE_SHEET_ID = "${VITE_GOOGLE_SHEET_ID}"
  VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}"
  VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}"
